# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
