# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161129_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DateField(default='1900-01-01', null=True),
        ),
    ]
