# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_customuser_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
