# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161129_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DateField(null=True),
        ),
    ]
