# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
