# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import sns_prj.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=sns_prj.custom_storage.RandomFileName('photo/default'))),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to=sns_prj.custom_storage.RandomFileName('photo/origin')),
        ),
    ]
