# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
