# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20161209_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 9, 20, 21, 45, 209304)),
        ),
    ]
