# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.AddField(
            model_name='post',
            name='view_counts',
            field=models.IntegerField(default=0),
        ),
    ]
