# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20161205_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modified_date',
        ),
    ]
