# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20161209_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
