# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='comment_counts',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
