# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20161211_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
