# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alarm_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='content',
        ),
    ]
